# Doctrine PostgreSQL Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: postgresql
        dbname: '%env(POSTGRES_DB)%'
        user: '%env(POSTGRES_USER)%'
        password: '%env(POSTGRES_PASSWORD)%'
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
