sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.17.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker -v
  - docker-compose -v

before_script:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop

script:
  - docker-compose -f docker-compose.yml -f docker-compose.mysql.yml config > docker-stack.yml
  - docker-compose -f docker-stack.yml build
  - docker-compose -f docker-stack.yml up -d
  - docker-compose -f docker-stack.yml ps
  - docker-compose -f docker-stack.yml stop
  - docker-compose -f docker-compose.yml -f docker-compose.postgresql.yml config > docker-stack.yml
  - docker-compose -f docker-stack.yml build
  - docker-compose -f docker-stack.yml up -d
  - docker-compose -f docker-stack.yml ps
  - docker-compose -f docker-stack.yml stop
  - docker-compose -f docker-compose.yml -f docker-compose.mongodb.yml config > docker-stack.yml
  - docker-compose -f docker-stack.yml build
  - docker-compose -f docker-stack.yml up -d
  - docker-compose -f docker-stack.yml ps
  - docker-compose -f docker-stack.yml stop