sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker -v
  - docker-compose -v

script:
  - make .env
  - make use-db DB=mysql
  - make install
  - make ps
  - make stop
  - make use-db DB=postgresql
  - make install
  - make ps
  - make stop
  - make use-db DB=mongodb
  - make install
  - make ps
  - make stop
