version: '3.2'

services:
  app:
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.mysql
    volumes:
      - ./.data/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"