version: '3.4'

services:
  app:
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}

  postgresql:
    image: postgres:10-alpine
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
