version: '3.2'

services:
  app:
    depends_on:
      - postgresql

  postgresql:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.postgresql
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"