version: '3.4'

services:
  app:
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}

  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - ./.data/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
