version: '3.4'

services:
  app:
    build:
      context: ./app
      target: symfony_docker_php
    volumes:
      - ./app:/srv:rw,cached
      - app_log:/srv/var/log
    environment:
      - REDIS_URL

  nginx:
    build:
      context: ./app
      target: symfony_docker_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./app/public:/srv/public:ro
      - nginx_log:/var/log/nginx
    command: nginx -g 'daemon off;'

  node:
    build:
      context: ./app
      target: symfony_docker_node
    volumes:
      - ./app:/srv:rw,cached

  redis:
    build:
      context: ./app
      target: symfony_docker_redis

  # elk:
  #   build:
  #     context: ./docker/elk
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #     - "5044:5044"
  #   environment:
  #     - ELASTICSEARCH_START
  #     - LOGSTASH_START
  #     - KIBANA_START
  #     - TZ

  # filebeat:
  #   build:
  #     context: ./docker/elk
  #     dockerfile: Dockerfile.filebeat
  #   volumes:
  #     - app_log:/var/log/app
  #     - nginx_log:/var/log/nginx

volumes:
  app_log:
  nginx_log:
