version: '3'

services:
  app:
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.mongodb
    volumes:
      - ./.data/mongo:/data/db:rw
    ports:
      - "27017:27017"
    command:
      - "--auth"