version: '3.2'

services:
  app:
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.mongodb
      args:
        - mongodb_username=${MONGODB_USERNAME}
        - mongodb_password=${MONGODB_PASSWORD}
        - mongodb_initdb_database=${MONGO_INITDB_DATABASE}
    volumes:
      - ./.data/mongo:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    ports:
      - "27017:27017"